//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kata.Wallet.Dtos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesDtos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesDtos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kata.Wallet.Dtos.Resources.MessagesDtos", typeof(MessagesDtos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción no puede superar los 255 caracteres.
        /// </summary>
        internal static string MaxLength_Description {
            get {
                return ResourceManager.GetString("MaxLength_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username no puede superar los 20 caracteres.
        /// </summary>
        internal static string MaxLength_UserName {
            get {
                return ResourceManager.GetString("MaxLength_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &apos;Documento&apos; debe tener al menos 8 caracteres..
        /// </summary>
        internal static string MinLength_Document {
            get {
                return ResourceManager.GetString("MinLength_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &apos;UserName&apos; debe tener al menos 5 caracteres..
        /// </summary>
        internal static string MinLength_UserName {
            get {
                return ResourceManager.GetString("MinLength_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El documento debe ser númerico.
        /// </summary>
        internal static string OnlyNumbers_Document {
            get {
                return ResourceManager.GetString("OnlyNumbers_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto debe ser positivo.
        /// </summary>
        internal static string Range_Amount {
            get {
                return ResourceManager.GetString("Range_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El balance no puede ser negativo..
        /// </summary>
        internal static string Range_Balance {
            get {
                return ResourceManager.GetString("Range_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe especificar un monto.
        /// </summary>
        internal static string Required_Amount {
            get {
                return ResourceManager.GetString("Required_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &apos;Balance&apos; es obligatorio..
        /// </summary>
        internal static string Required_Balance {
            get {
                return ResourceManager.GetString("Required_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La &apos;Moneda&apos; es obligatoria..
        /// </summary>
        internal static string Required_Currency {
            get {
                return ResourceManager.GetString("Required_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &apos;Documento&apos; es obligatorio..
        /// </summary>
        internal static string Required_Document {
            get {
                return ResourceManager.GetString("Required_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El &apos;UserName&apos; es obligatorio..
        /// </summary>
        internal static string Required_UserName {
            get {
                return ResourceManager.GetString("Required_UserName", resourceCulture);
            }
        }
    }
}
